name: Build on pull request change (mvn package)

on:
  workflow_call:
    inputs:
      skip-integration-tests:
        description: 'Skip integration tests true/false'
        default: false
        required: false
        type: boolean
    secrets:
      ACCESS_PACKAGES_USERNAME:
        required: true
      ACCESS_PACKAGES_GLOBAL_PAT:
        required: true
      OUR_GITHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14 for Maven Building
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create settings.xml
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: '
            [
              {
                "id": "github",
                "username": "${{ secrets.ACCESS_PACKAGES_USERNAME }}",
                "password": "${{ secrets.ACCESS_PACKAGES_GLOBAL_PAT }}"
              }
            ]'
          repositories: '
            [
                {
                  "id": "github",
                  "name": "Nordea Direct Github",
                  "url": "https://maven.pkg.github.com/Nordea-Direct/*",
                  "snapshots": {
                    "enabled": "true"
                  }
                }
            ]'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -Dmaven.test.skip=${{ inputs.skip-integration-tests }}
        env:
          GITHUB_TOKEN: ${{ secrets.OUR_GITHUB_TOKEN }}
