name: Build and deploy application to Github Packages Maven repo (mvn deploy)

on:
  workflow_call:
    inputs:
      build-folder:
        description: 'Where the build folder resides'
        default: 'dist'
        required: false
        type: string
    secrets:
      NORDEABOT_PRIVATE_KEY:
        required: true
      ACCESS_PACKAGES_USERNAME:
        required: true
      ACCESS_PACKAGES_GLOBAL_PAT:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.ACCESS_PACKAGES_GLOBAL_PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - run: npm install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build application
        env:
          NODE_ENV: production
        run: npm run build:ci

      - name: Change folder name to dist and zip it
        run: cd ${{ inputs.build-folder }} && ls -ltra . && zip -r release.zip *

      - name: Set up JDK 14 for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Create settings.xml
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: '
              [
                {
                  "id": "github",
                  "username": "${{ secrets.ACCESS_PACKAGES_USERNAME }}",
                  "password": "${{ secrets.ACCESS_PACKAGES_GLOBAL_PAT }}"
                }
              ]'
          repositories: '
              [
                  {
                    "id": "github",
                    "name": "Nordea Direct Github",
                    "url": "https://maven.pkg.github.com/Nordea-Direct/*",
                    "snapshots": {
                      "enabled": "true"
                    }
                  }
              ]'

      - name: Upload package
        run: |
          mvn deploy:deploy-file \
            -DpomFile=pom.xml \
            -Dpackaging=zip \
            -Dfile=${{ inputs.build-folder }}/release.zip \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/${{ github.repository }}





