name: Deploy to Github Packages on manual workflow run (mvn deploy)

on:
  workflow_call:
    secrets:
      NORDEABOT_PRIVATE_KEY:
        required: true
      ACCESS_PACKAGES_USERNAME:
        required: true
      ACCESS_PACKAGES_GLOBAL_PAT:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - run: npm install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build application
        env:
          NODE_ENV: production
        run: npm run build:ci

      - name: Change folder name to dist and zip it
        run: cd ${{ inputs.build-folder }} && ls -ltra . && zip -r release.zip *

      - name: Set up JDK 14 for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Creating SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.NORDEABOT_PRIVATE_KEY }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: 'Create settings.xml'
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: '
            [
              {
                "id": "github",
                "username": "${{ secrets.ACCESS_PACKAGES_USERNAME }}",
                "password": "${{ secrets.ACCESS_PACKAGES_GLOBAL_PAT }}"
              }
            ]'
          repositories: '
            [
                {
                  "id": "github",
                  "name": "Nordea Direct Github",
                  "url": "https://maven.pkg.github.com/Nordea-Direct/*",
                  "snapshots": {
                    "enabled": "true"
                  }
                }
            ]'
      - name: Configure Git user
        run: |
          git config user.email "espen.erlandsen@nordea.com"
          git config user.name "nordeadirect-bot"
      - uses: actions/checkout@v2
        name: Checking out Git repo with defined TAG
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Build with Maven and deploy to Github Packages
        run: mvn --update-snapshots --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}